# Generated by Django 2.0.4 on 2018-05-19 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180519_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Section', verbose_name='Seccion'),
        ),
    ]
