# Generated by Django 2.0.4 on 2018-05-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number_employee',
            field=models.CharField(max_length=15, null=True, verbose_name='AC No.'),
        ),
    ]
