# Generated by Django 2.0.4 on 2018-05-27 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180526_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('level', models.SmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'verbose_name': 'Nivel de pago',
                'verbose_name_plural': 'Niveles de pago',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.Section', verbose_name='Seccion'),
        ),
    ]
