# Generated by Django 2.0.4 on 2018-06-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180527_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('position_name', models.CharField(max_length=30, verbose_name='Nombre del cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.AlterField(
            model_name='paymentscale',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
