# Generated by Django 2.0.4 on 2018-06-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180617_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Increment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('percentage', models.IntegerField(verbose_name='Porcentaje de incremento')),
            ],
            options={
                'verbose_name': 'Incremento',
                'verbose_name_plural': 'Incrementos',
            },
        ),
    ]
