# Generated by Django 2.0.4 on 2018-06-17 21:44

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_increment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentscale',
            name='level',
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Position', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='paymentscale',
            name='position',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Position', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Teléfono/Celular'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_path_files, verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.Section', verbose_name='Sección'),
        ),
    ]
