# Generated by Django 2.0.4 on 2018-08-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUploaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creado')),
                ('updated', models.DateTimeField(editable=False, verbose_name='Modificado')),
                ('file', models.FileField(upload_to='uploads/registers/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('created', 'Creado'), ('processing', 'Procesando'), ('success', 'Finalizado'), ('error', 'Error')], max_length=15)),
                ('result', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
