# Generated by Django 2.0.4 on 2018-08-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeruploaded',
            options={'verbose_name': 'Registro subido', 'verbose_name_plural': 'Registros subidos'},
        ),
        migrations.AlterField(
            model_name='registeruploaded',
            name='file',
            field=models.FileField(upload_to='uploads/registers/%Y/%m/%d/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='registeruploaded',
            name='result',
            field=models.TextField(null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='registeruploaded',
            name='status',
            field=models.CharField(choices=[('created', 'Creado'), ('processing', 'Procesando'), ('success', 'Finalizado'), ('error', 'Error'), ('canceled', 'Cancelado')], default='created', max_length=15, verbose_name='Estado'),
        ),
    ]
