# Generated by Django 2.0.4 on 2018-06-04 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('start_work', models.DateTimeField(verbose_name='Fecha/Hora inicio')),
                ('end_work', models.DateTimeField(verbose_name='Fecha/Hora termino')),
                ('is_recurring', models.BooleanField(default=True, verbose_name='es recurrente')),
                ('descripction', models.TextField(null=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_scheduler_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
                ('parent_event', models.ForeignKey(blank=True, null=True, on_delete=None, to='schedules.Scheduler', verbose_name='Panificado padre')),
            ],
            options={
                'verbose_name': 'Planificado',
                'verbose_name_plural': 'Planificados',
            },
        ),
        migrations.CreateModel(
            name='SchedulerException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('is_rescheduled', models.BooleanField(verbose_name='Es reprogramado')),
                ('is_cancelled', models.BooleanField(verbose_name='Es cancelado')),
                ('start_datetime', models.DateTimeField(verbose_name='Fecha/Hora inicio')),
                ('end_datetime', models.DateTimeField(verbose_name='Fecha/Hora termino')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('scheduler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.Scheduler', verbose_name='Panificador')),
            ],
            options={
                'verbose_name': 'Ocurrencia planificador',
                'verbose_name_plural': 'Ocurrencias planificador',
            },
        ),
        migrations.CreateModel(
            name='SchedulerRecurringPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('separation_count', models.PositiveIntegerField(default=0, verbose_name='Conteo separacion')),
                ('max_num_occurrences', models.PositiveIntegerField(default=0, verbose_name='Max. num. ocurrencias')),
                ('day_of_week', models.PositiveSmallIntegerField(default=0, verbose_name='Dia de la semana')),
                ('week_of_month', models.PositiveSmallIntegerField(default=0, verbose_name='Semana del mes')),
                ('day_of_month', models.PositiveSmallIntegerField(default=0, verbose_name='Dia del mes')),
                ('month_of_year', models.PositiveSmallIntegerField(default=0, verbose_name='Mes del an~o')),
                ('scheduler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.Scheduler', verbose_name='Panificador')),
            ],
            options={
                'verbose_name': 'Patron recurrente',
                'verbose_name_plural': 'Patrones recurrentes',
            },
        ),
        migrations.CreateModel(
            name='TimeOfDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=150)),
                ('start_datetime', models.DateTimeField(verbose_name='Fecha/Hora inicio')),
                ('end_datetime', models.DateTimeField(verbose_name='Fecha/Hora termino')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='parent_event',
        ),
        migrations.RemoveField(
            model_name='eventexception',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='eventexception',
            name='event',
        ),
        migrations.RemoveField(
            model_name='recurringpattern',
            name='event',
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_activity_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_employee', to=settings.AUTH_USER_MODEL, verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_work',
            field=models.DateTimeField(verbose_name='Fecha/Hora termino'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_work',
            field=models.DateTimeField(verbose_name='Fecha/Hora inicio'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventException',
        ),
        migrations.DeleteModel(
            name='RecurringPattern',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='timeofday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.TimeOfDay'),
        ),
    ]
