# Generated by Django 2.0.4 on 2018-06-06 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20180604_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerDay',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('schedules.scheduler',),
        ),
        migrations.CreateModel(
            name='SchedulerMonth',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('schedules.scheduler',),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='descripction',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='is_recurring',
            field=models.BooleanField(default=True, verbose_name='Es recurrente'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='schedules.Scheduler', verbose_name='Planificado origen'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='timeofday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.TimeOfDay', verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='schedulerexception',
            name='scheduler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.Scheduler', verbose_name='Planificador'),
        ),
        migrations.AlterField(
            model_name='schedulerrecurringpattern',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Día del mes'),
        ),
        migrations.AlterField(
            model_name='schedulerrecurringpattern',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Día de la semana'),
        ),
        migrations.AlterField(
            model_name='schedulerrecurringpattern',
            name='month_of_year',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Mes del año'),
        ),
        migrations.AlterField(
            model_name='schedulerrecurringpattern',
            name='scheduler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.Scheduler', verbose_name='Planificador'),
        ),
        migrations.AlterField(
            model_name='schedulerrecurringpattern',
            name='separation_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Conteo separación'),
        ),
        migrations.AlterField(
            model_name='schedulerrecurringpattern',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
    ]
