# Generated by Django 2.0.4 on 2018-06-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20180606_0208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulerday',
            options={'verbose_name': 'Calendario Día'},
        ),
        migrations.AlterModelOptions(
            name='schedulermonth',
            options={'verbose_name': 'Calendario Mes'},
        ),
        migrations.RemoveField(
            model_name='timeofday',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='timeofday',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='timeofday',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Hora termino'),
        ),
        migrations.AddField(
            model_name='timeofday',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Hora inicio'),
        ),
    ]
