# Generated by Django 2.0.4 on 2018-06-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20180607_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_work',
            field=models.DateTimeField(null=True, verbose_name='Fecha/Hora termino'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_work',
            field=models.DateTimeField(null=True, verbose_name='Fecha/Hora inicio'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='end_work',
            field=models.DateTimeField(null=True, verbose_name='Fecha/Hora termino'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='start_work',
            field=models.DateTimeField(null=True, verbose_name='Fecha/Hora inicio'),
        ),
    ]
