# Generated by Django 2.0.4 on 2018-07-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20180607_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(editable=False, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_work',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora termino'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_work',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora inicio'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated',
            field=models.DateTimeField(editable=False, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='created',
            field=models.DateTimeField(editable=False, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='end_work',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora termino'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='start_work',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora inicio'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='updated',
            field=models.DateTimeField(editable=False, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='schedulerexception',
            name='created',
            field=models.DateTimeField(editable=False, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='schedulerexception',
            name='updated',
            field=models.DateTimeField(editable=False, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='schedulerrecurringpattern',
            name='created',
            field=models.DateTimeField(editable=False, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='schedulerrecurringpattern',
            name='updated',
            field=models.DateTimeField(editable=False, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='timeofday',
            name='created',
            field=models.DateTimeField(editable=False, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='timeofday',
            name='updated',
            field=models.DateTimeField(editable=False, verbose_name='Modificado'),
        ),
    ]
