# Generated by Django 2.0.4 on 2018-07-19 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20180714_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='end_work',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_work',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='end_work',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='start_work',
        ),
        migrations.AddField(
            model_name='activity',
            name='day',
            field=models.DateField(blank=True, null=True, verbose_name='Dia'),
        ),
        migrations.AddField(
            model_name='activity',
            name='timeofday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.TimeOfDay', verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='day',
            field=models.DateField(blank=True, null=True, verbose_name='Dia'),
        ),
    ]
