# Generated by Django 2.0.4 on 2018-08-09 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_auto_20180719_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='day',
            field=models.DateField(null=True, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='timeofday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.TimeOfDay', verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='day',
            field=models.DateField(null=True, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='timeofday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.TimeOfDay', verbose_name='Periodo'),
        ),
    ]
