# Generated by Django 2.0.4 on 2018-08-29 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0008_auto_20180809_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerrecurringpattern',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_schedulerrecurringpattern_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='timeofday',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_timeofday_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
