# Generated by Django 2.0.4 on 2018-12-18 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_auto_20180829_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
            ],
            options={
                'verbose_name': 'Calendaros',
                'verbose_name_plural': 'Calendarios',
                'proxy': True,
                'indexes': [],
            },
            bases=('schedules.scheduler',),
        ),
    ]
